"""add channels.kind for direct conversations

Revision ID: 68ade9fc12cb
Revises: 5af91b8080b2
Create Date: 2026-08-16 15:24:11.814034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ade9fc12cb'
down_revision: Union[str, None] = '5af91b8080b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'channels',
        sa.Column(
            'kind', sa.String(length=10), nullable=False, server_default='group'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'kind')
    # ### end Alembic commands ###
