"""add notification preferences tables

Revision ID: c3d9b4e5f6a7
Revises: a1f42c8d9e77
Create Date: 2026-08-17 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d9b4e5f6a7'
down_revision: Union[str, None] = 'a1f42c8d9e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_notification_settings',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('global_enabled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_notif_settings_user'),
        sa.PrimaryKeyConstraint('user_id', name='pk_user_notif_settings'),
    )
    op.create_table(
        'channel_notification_settings',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='fk_channel_notif_settings_channel'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_channel_notif_settings_user'),
        sa.PrimaryKeyConstraint('user_id', 'channel_id', name='pk_channel_notif_settings'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_notification_settings')
    op.drop_table('user_notification_settings')
    # ### end Alembic commands ###