"""widen notifications content to text

Revision ID: d0626a07e831
Revises: c3d9b4e5f6a7
Create Date: 2026-08-17 17:07:54.193379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0626a07e831'
down_revision: Union[str, None] = 'c3d9b4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.alter_column('content',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.Text(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.alter_column('content',
                   existing_type=sa.Text(),
                   type_=sa.VARCHAR(length=255),
                   existing_nullable=False)
    # ### end Alembic commands ###
